/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "gui.h"
#include "support.h"

GtkWidget*
create_xat (void)
{
  GtkWidget *xat;
  GtkWidget *vbox;
  GtkWidget *notebook;
  GtkWidget *scrolledwindow;
  GtkWidget *viewport;
  GtkWidget *tbl_info;
  GtkWidget *lbl_i_name;
  GtkWidget *lbl_iv_mime;
  GtkWidget *lbl_iv_mtime;
  GtkWidget *lbl_iv_atime;
  GtkWidget *lbl_iv_type;
  GtkWidget *lbl_i_type;
  GtkWidget *lbl_i_mime;
  GtkWidget *lbl_i_size;
  GtkWidget *lbl_i_atime;
  GtkWidget *lbl_i_mtime;
  GtkWidget *lbl_i_ad_type;
  GtkWidget *lbl_i_ad_creator;
  GtkWidget *lbl_iv_ad_type;
  GtkWidget *lbl_iv_ad_creator;
  GtkWidget *en_iv_name;
  guint btn_diskusage_key;
  GtkWidget *btn_diskusage;
  GtkWidget *lbl_iv_size;
  GtkWidget *lbl_info;
  GtkWidget *tbl_perms;
  GtkWidget *frame_op;
  GtkWidget *vbox2;
  GSList *rg_ops_group = NULL;
  guint rb_set_key;
  GtkWidget *rb_set;
  guint rb_add_key;
  GtkWidget *rb_add;
  guint rb_remove_key;
  GtkWidget *rb_remove;
  GtkWidget *cb_o_write;
  GtkWidget *cb_o_exec;
  GtkWidget *cb_g_write;
  GtkWidget *cb_g_exec;
  GtkWidget *cb_u_write;
  GtkWidget *cb_u_exec;
  guint cb_changeperms_key;
  GtkWidget *cb_changeperms;
  GtkWidget *cb_u_read;
  GtkWidget *cb_g_read;
  GtkWidget *cb_o_read;
  GtkWidget *cb_set_uid;
  GtkWidget *cb_set_gid;
  GtkWidget *cb_set_sticky;
  GtkWidget *lbl_i_group;
  GtkWidget *lbl_i_other;
  GtkWidget *lbl_i_owner;
  GtkWidget *frame_owner;
  GtkWidget *hbox1;
  GtkWidget *combo_owner;
  GtkWidget *centry_owner;
  GtkWidget *cb_changeowner;
  GtkWidget *frame_group;
  GtkWidget *hbox2;
  GtkWidget *combo_group;
  GtkWidget *centry_group;
  guint cb_changegroup_key;
  GtkWidget *cb_changegroup;
  GtkWidget *vseparator;
  GtkWidget *frame_opts;
  guint cbtn_subdirs_key;
  GtkWidget *cbtn_subdirs;
  GtkWidget *lbl_note;
  GtkWidget *lbl_perms;
  GtkWidget *hbox;
  guint btn_ok_key;
  GtkWidget *btn_ok;
  guint btn_skip_key;
  GtkWidget *btn_skip;
  guint btn_all_key;
  GtkWidget *btn_all;
  guint btn_cancel_key;
  GtkWidget *btn_cancel;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  xat = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (xat), "xat", xat);
  gtk_window_set_title (GTK_WINDOW (xat), "X attribute change");

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox);
  gtk_object_set_data_full (GTK_OBJECT (xat), "vbox", vbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (xat), vbox);

  notebook = gtk_notebook_new ();
  gtk_widget_ref (notebook);
  gtk_object_set_data_full (GTK_OBJECT (xat), "notebook", notebook,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook);
  gtk_box_pack_start (GTK_BOX (vbox), notebook, TRUE, TRUE, 0);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (notebook), TRUE);

  scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow);
  gtk_object_set_data_full (GTK_OBJECT (xat), "scrolledwindow", scrolledwindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow);
  gtk_container_add (GTK_CONTAINER (notebook), scrolledwindow);

  viewport = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport);
  gtk_object_set_data_full (GTK_OBJECT (xat), "viewport", viewport,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport);
  gtk_container_add (GTK_CONTAINER (scrolledwindow), viewport);

  tbl_info = gtk_table_new (9, 3, FALSE);
  gtk_widget_ref (tbl_info);
  gtk_object_set_data_full (GTK_OBJECT (xat), "tbl_info", tbl_info,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tbl_info);
  gtk_container_add (GTK_CONTAINER (viewport), tbl_info);
  gtk_container_set_border_width (GTK_CONTAINER (tbl_info), 2);
  gtk_table_set_row_spacings (GTK_TABLE (tbl_info), 2);
  gtk_table_set_col_spacings (GTK_TABLE (tbl_info), 2);

  lbl_i_name = gtk_label_new ("Name:");
  gtk_widget_ref (lbl_i_name);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_name", lbl_i_name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_name);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_i_name, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_i_name), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_name), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_name), 4, 2);

  lbl_iv_mime = gtk_label_new ("<none>");
  gtk_widget_ref (lbl_iv_mime);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_iv_mime", lbl_iv_mime,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_iv_mime);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_iv_mime, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_iv_mime), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lbl_iv_mime), 0, 0.5);

  lbl_iv_mtime = gtk_label_new ("<none>");
  gtk_widget_ref (lbl_iv_mtime);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_iv_mtime", lbl_iv_mtime,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_iv_mtime);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_iv_mtime, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_iv_mtime), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lbl_iv_mtime), 0, 0.5);

  lbl_iv_atime = gtk_label_new ("<none>");
  gtk_widget_ref (lbl_iv_atime);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_iv_atime", lbl_iv_atime,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_iv_atime);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_iv_atime, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_iv_atime), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lbl_iv_atime), 0, 0.5);

  lbl_iv_type = gtk_label_new ("<none>");
  gtk_widget_ref (lbl_iv_type);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_iv_type", lbl_iv_type,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_iv_type);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_iv_type, 1, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_iv_type), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lbl_iv_type), 0, 0.5);

  lbl_i_type = gtk_label_new ("Type:");
  gtk_widget_ref (lbl_i_type);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_type", lbl_i_type,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_type);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_i_type, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_i_type), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_type), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_type), 4, 2);

  lbl_i_mime = gtk_label_new ("MIME:");
  gtk_widget_ref (lbl_i_mime);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_mime", lbl_i_mime,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_mime);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_i_mime, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_i_mime), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_mime), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_mime), 4, 2);

  lbl_i_size = gtk_label_new ("Size (byte):");
  gtk_widget_ref (lbl_i_size);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_size", lbl_i_size,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_size);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_i_size, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_i_size), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_size), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_size), 4, 2);

  lbl_i_atime = gtk_label_new ("Access Time:");
  gtk_widget_ref (lbl_i_atime);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_atime", lbl_i_atime,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_atime);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_i_atime, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_i_atime), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_atime), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_atime), 4, 2);

  lbl_i_mtime = gtk_label_new ("Modif. Time:");
  gtk_widget_ref (lbl_i_mtime);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_mtime", lbl_i_mtime,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_mtime);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_i_mtime, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_i_mtime), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_mtime), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_mtime), 4, 2);

  lbl_i_ad_type = gtk_label_new ("AD Type:");
  gtk_widget_ref (lbl_i_ad_type);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_ad_type", lbl_i_ad_type,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_ad_type);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_i_ad_type, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_i_ad_type), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_ad_type), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_ad_type), 4, 2);

  lbl_i_ad_creator = gtk_label_new ("AD Creator:");
  gtk_widget_ref (lbl_i_ad_creator);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_ad_creator", lbl_i_ad_creator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_ad_creator);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_i_ad_creator, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_i_ad_creator), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_ad_creator), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_ad_creator), 4, 2);

  lbl_iv_ad_type = gtk_label_new ("<not supported until now>");
  gtk_widget_ref (lbl_iv_ad_type);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_iv_ad_type", lbl_iv_ad_type,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_iv_ad_type);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_iv_ad_type, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_iv_ad_type), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lbl_iv_ad_type), 0, 0.5);

  lbl_iv_ad_creator = gtk_label_new ("<not supported until now>");
  gtk_widget_ref (lbl_iv_ad_creator);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_iv_ad_creator", lbl_iv_ad_creator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_iv_ad_creator);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_iv_ad_creator, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_iv_ad_creator), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lbl_iv_ad_creator), 0, 0.5);

  en_iv_name = gtk_entry_new ();
  gtk_widget_ref (en_iv_name);
  gtk_object_set_data_full (GTK_OBJECT (xat), "en_iv_name", en_iv_name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (en_iv_name);
  gtk_table_attach (GTK_TABLE (tbl_info), en_iv_name, 1, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_editable (GTK_ENTRY (en_iv_name), FALSE);

  btn_diskusage = gtk_button_new_with_label ("");
  btn_diskusage_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (btn_diskusage)->child),
                                   "Calculate Disk _Usage");
  gtk_widget_add_accelerator (btn_diskusage, "clicked", accel_group,
                              btn_diskusage_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (btn_diskusage);
  gtk_object_set_data_full (GTK_OBJECT (xat), "btn_diskusage", btn_diskusage,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_table_attach (GTK_TABLE (tbl_info), btn_diskusage, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lbl_iv_size = gtk_label_new ("<none>");
  gtk_widget_ref (lbl_iv_size);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_iv_size", lbl_iv_size,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_iv_size);
  gtk_table_attach (GTK_TABLE (tbl_info), lbl_iv_size, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_iv_size), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lbl_iv_size), 0, 0.5);

  lbl_info = gtk_label_new ("Information");
  gtk_widget_ref (lbl_info);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_info", lbl_info,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_info);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), lbl_info);

  tbl_perms = gtk_table_new (5, 7, FALSE);
  gtk_widget_ref (tbl_perms);
  gtk_object_set_data_full (GTK_OBJECT (xat), "tbl_perms", tbl_perms,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tbl_perms);
  gtk_container_add (GTK_CONTAINER (notebook), tbl_perms);
  gtk_container_set_border_width (GTK_CONTAINER (tbl_perms), 2);
  gtk_table_set_row_spacings (GTK_TABLE (tbl_perms), 1);
  gtk_table_set_col_spacings (GTK_TABLE (tbl_perms), 2);

  frame_op = gtk_frame_new ("Operator");
  gtk_widget_ref (frame_op);
  gtk_object_set_data_full (GTK_OBJECT (xat), "frame_op", frame_op,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_op);
  gtk_table_attach (GTK_TABLE (tbl_perms), frame_op, 0, 5, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_op), 4);
  gtk_widget_set_sensitive (frame_op, FALSE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (xat), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frame_op), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 2);

  rb_set = gtk_radio_button_new_with_label (rg_ops_group, "");
  rb_set_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (rb_set)->child),
                                   "_Set permissions as above");
  gtk_widget_add_accelerator (rb_set, "clicked", accel_group,
                              rb_set_key, GDK_MOD1_MASK, 0);
  rg_ops_group = gtk_radio_button_group (GTK_RADIO_BUTTON (rb_set));
  gtk_widget_ref (rb_set);
  gtk_object_set_data_full (GTK_OBJECT (xat), "rb_set", rb_set,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rb_set);
  gtk_box_pack_start (GTK_BOX (vbox2), rb_set, FALSE, FALSE, 0);

  rb_add = gtk_radio_button_new_with_label (rg_ops_group, "");
  rb_add_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (rb_add)->child),
                                   "A_dd permissions (logical OR'ed)");
  gtk_widget_add_accelerator (rb_add, "clicked", accel_group,
                              rb_add_key, GDK_MOD1_MASK, 0);
  rg_ops_group = gtk_radio_button_group (GTK_RADIO_BUTTON (rb_add));
  gtk_widget_ref (rb_add);
  gtk_object_set_data_full (GTK_OBJECT (xat), "rb_add", rb_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rb_add);
  gtk_box_pack_start (GTK_BOX (vbox2), rb_add, FALSE, FALSE, 0);

  rb_remove = gtk_radio_button_new_with_label (rg_ops_group, "");
  rb_remove_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (rb_remove)->child),
                                   "_Remove permissions which are marked above");
  gtk_widget_add_accelerator (rb_remove, "clicked", accel_group,
                              rb_remove_key, GDK_MOD1_MASK, 0);
  rg_ops_group = gtk_radio_button_group (GTK_RADIO_BUTTON (rb_remove));
  gtk_widget_ref (rb_remove);
  gtk_object_set_data_full (GTK_OBJECT (xat), "rb_remove", rb_remove,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rb_remove);
  gtk_box_pack_start (GTK_BOX (vbox2), rb_remove, FALSE, FALSE, 0);

  cb_o_write = gtk_check_button_new_with_label ("Write");
  gtk_widget_ref (cb_o_write);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_o_write", cb_o_write,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_o_write);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_o_write, 2, 3, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  cb_o_exec = gtk_check_button_new_with_label ("Execute");
  gtk_widget_ref (cb_o_exec);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_o_exec", cb_o_exec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_o_exec);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_o_exec, 3, 4, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  cb_g_write = gtk_check_button_new_with_label ("Write");
  gtk_widget_ref (cb_g_write);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_g_write", cb_g_write,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_g_write);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_g_write, 2, 3, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  cb_g_exec = gtk_check_button_new_with_label ("Execute");
  gtk_widget_ref (cb_g_exec);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_g_exec", cb_g_exec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_g_exec);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_g_exec, 3, 4, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  cb_u_write = gtk_check_button_new_with_label ("Write");
  gtk_widget_ref (cb_u_write);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_u_write", cb_u_write,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_u_write);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_u_write, 2, 3, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  cb_u_exec = gtk_check_button_new_with_label ("Execute");
  gtk_widget_ref (cb_u_exec);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_u_exec", cb_u_exec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_u_exec);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_u_exec, 3, 4, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  cb_changeperms = gtk_check_button_new_with_label ("");
  cb_changeperms_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (cb_changeperms)->child),
                                   "Change _Permissions");
  gtk_widget_add_accelerator (cb_changeperms, "clicked", accel_group,
                              cb_changeperms_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (cb_changeperms);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_changeperms", cb_changeperms,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_changeperms);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_changeperms, 0, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  cb_u_read = gtk_check_button_new_with_label ("Read");
  gtk_widget_ref (cb_u_read);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_u_read", cb_u_read,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_u_read);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_u_read, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  cb_g_read = gtk_check_button_new_with_label ("Read");
  gtk_widget_ref (cb_g_read);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_g_read", cb_g_read,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_g_read);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_g_read, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  cb_o_read = gtk_check_button_new_with_label ("Read");
  gtk_widget_ref (cb_o_read);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_o_read", cb_o_read,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_o_read);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_o_read, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  cb_set_uid = gtk_check_button_new_with_label ("Set user ID");
  gtk_widget_ref (cb_set_uid);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_set_uid", cb_set_uid,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_set_uid);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_set_uid, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  cb_set_gid = gtk_check_button_new_with_label ("Set group ID");
  gtk_widget_ref (cb_set_gid);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_set_gid", cb_set_gid,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_set_gid);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_set_gid, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  cb_set_sticky = gtk_check_button_new_with_label ("Sticky Bit");
  gtk_widget_ref (cb_set_sticky);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_set_sticky", cb_set_sticky,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_set_sticky);
  gtk_table_attach (GTK_TABLE (tbl_perms), cb_set_sticky, 4, 5, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  lbl_i_group = gtk_label_new ("Group:");
  gtk_widget_ref (lbl_i_group);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_group", lbl_i_group,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_group);
  gtk_table_attach (GTK_TABLE (tbl_perms), lbl_i_group, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lbl_i_group, FALSE);
  gtk_label_set_justify (GTK_LABEL (lbl_i_group), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_group), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_group), 4, 2);

  lbl_i_other = gtk_label_new ("Others:");
  gtk_widget_ref (lbl_i_other);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_other", lbl_i_other,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_other);
  gtk_table_attach (GTK_TABLE (tbl_perms), lbl_i_other, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lbl_i_other, FALSE);
  gtk_label_set_justify (GTK_LABEL (lbl_i_other), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_other), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_other), 4, 2);

  lbl_i_owner = gtk_label_new ("Owner:");
  gtk_widget_ref (lbl_i_owner);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_i_owner", lbl_i_owner,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_i_owner);
  gtk_table_attach (GTK_TABLE (tbl_perms), lbl_i_owner, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (lbl_i_owner, FALSE);
  gtk_label_set_justify (GTK_LABEL (lbl_i_owner), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (lbl_i_owner), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_i_owner), 4, 2);

  frame_owner = gtk_frame_new (NULL);
  gtk_widget_ref (frame_owner);
  gtk_object_set_data_full (GTK_OBJECT (xat), "frame_owner", frame_owner,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_owner);
  gtk_table_attach (GTK_TABLE (tbl_perms), frame_owner, 6, 7, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_owner), 1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (xat), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (frame_owner), hbox1);

  combo_owner = gtk_combo_new ();
  gtk_widget_ref (combo_owner);
  gtk_object_set_data_full (GTK_OBJECT (xat), "combo_owner", combo_owner,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_owner);
  gtk_box_pack_start (GTK_BOX (hbox1), combo_owner, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (combo_owner, FALSE);

  centry_owner = GTK_COMBO (combo_owner)->entry;
  gtk_widget_ref (centry_owner);
  gtk_object_set_data_full (GTK_OBJECT (xat), "centry_owner", centry_owner,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (centry_owner);

  cb_changeowner = gtk_check_button_new_with_label ("change");
  gtk_widget_ref (cb_changeowner);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_changeowner", cb_changeowner,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_changeowner);
  gtk_box_pack_start (GTK_BOX (hbox1), cb_changeowner, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (cb_changeowner), 2);

  frame_group = gtk_frame_new (NULL);
  gtk_widget_ref (frame_group);
  gtk_object_set_data_full (GTK_OBJECT (xat), "frame_group", frame_group,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_group);
  gtk_table_attach (GTK_TABLE (tbl_perms), frame_group, 6, 7, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_group), 1);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (xat), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (frame_group), hbox2);

  combo_group = gtk_combo_new ();
  gtk_widget_ref (combo_group);
  gtk_object_set_data_full (GTK_OBJECT (xat), "combo_group", combo_group,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_group);
  gtk_box_pack_start (GTK_BOX (hbox2), combo_group, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (combo_group, FALSE);

  centry_group = GTK_COMBO (combo_group)->entry;
  gtk_widget_ref (centry_group);
  gtk_object_set_data_full (GTK_OBJECT (xat), "centry_group", centry_group,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (centry_group);

  cb_changegroup = gtk_check_button_new_with_label ("");
  cb_changegroup_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (cb_changegroup)->child),
                                   "c_hange");
  gtk_widget_add_accelerator (cb_changegroup, "clicked", accel_group,
                              cb_changegroup_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (cb_changegroup);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cb_changegroup", cb_changegroup,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cb_changegroup);
  gtk_box_pack_start (GTK_BOX (hbox2), cb_changegroup, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (cb_changegroup), 2);

  vseparator = gtk_vseparator_new ();
  gtk_widget_ref (vseparator);
  gtk_object_set_data_full (GTK_OBJECT (xat), "vseparator", vseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator);
  gtk_table_attach (GTK_TABLE (tbl_perms), vseparator, 5, 6, 0, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_FILL), 2, 0);

  frame_opts = gtk_frame_new ("Options");
  gtk_widget_ref (frame_opts);
  gtk_object_set_data_full (GTK_OBJECT (xat), "frame_opts", frame_opts,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame_opts);
  gtk_table_attach (GTK_TABLE (tbl_perms), frame_opts, 6, 7, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  cbtn_subdirs = gtk_check_button_new_with_label ("");
  cbtn_subdirs_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (cbtn_subdirs)->child),
                                   "Include _subdirectories and it's files.");
  gtk_widget_add_accelerator (cbtn_subdirs, "clicked", accel_group,
                              cbtn_subdirs_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (cbtn_subdirs);
  gtk_object_set_data_full (GTK_OBJECT (xat), "cbtn_subdirs", cbtn_subdirs,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cbtn_subdirs);
  gtk_container_add (GTK_CONTAINER (frame_opts), cbtn_subdirs);
  gtk_container_set_border_width (GTK_CONTAINER (cbtn_subdirs), 2);

  lbl_note = gtk_label_new ("Note: Only 'root' can change the owner.");
  gtk_widget_ref (lbl_note);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_note", lbl_note,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_note);
  gtk_table_attach (GTK_TABLE (tbl_perms), lbl_note, 6, 7, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (lbl_note), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (lbl_note), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (lbl_note), 0, 6);

  lbl_perms = gtk_label_new ("Permissions");
  gtk_widget_ref (lbl_perms);
  gtk_object_set_data_full (GTK_OBJECT (xat), "lbl_perms", lbl_perms,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbl_perms);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), lbl_perms);

  hbox = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox);
  gtk_object_set_data_full (GTK_OBJECT (xat), "hbox", hbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox);
  gtk_box_pack_start (GTK_BOX (vbox), hbox, TRUE, TRUE, 2);

  btn_ok = gtk_button_new_with_label ("");
  btn_ok_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (btn_ok)->child),
                                   "_OK");
  gtk_widget_add_accelerator (btn_ok, "clicked", accel_group,
                              btn_ok_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (btn_ok);
  gtk_object_set_data_full (GTK_OBJECT (xat), "btn_ok", btn_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btn_ok);
  gtk_box_pack_start (GTK_BOX (hbox), btn_ok, FALSE, TRUE, 8);
  gtk_container_set_border_width (GTK_CONTAINER (btn_ok), 4);

  btn_skip = gtk_button_new_with_label ("");
  btn_skip_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (btn_skip)->child),
                                   "S_kip");
  gtk_widget_add_accelerator (btn_skip, "clicked", accel_group,
                              btn_skip_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (btn_skip);
  gtk_object_set_data_full (GTK_OBJECT (xat), "btn_skip", btn_skip,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btn_skip);
  gtk_box_pack_start (GTK_BOX (hbox), btn_skip, FALSE, TRUE, 8);
  gtk_container_set_border_width (GTK_CONTAINER (btn_skip), 4);

  btn_all = gtk_button_new_with_label ("");
  btn_all_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (btn_all)->child),
                                   "_All");
  gtk_widget_add_accelerator (btn_all, "clicked", accel_group,
                              btn_all_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (btn_all);
  gtk_object_set_data_full (GTK_OBJECT (xat), "btn_all", btn_all,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btn_all);
  gtk_box_pack_start (GTK_BOX (hbox), btn_all, FALSE, TRUE, 8);
  gtk_container_set_border_width (GTK_CONTAINER (btn_all), 4);

  btn_cancel = gtk_button_new_with_label ("");
  btn_cancel_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (btn_cancel)->child),
                                   "_Cancel");
  gtk_widget_add_accelerator (btn_cancel, "clicked", accel_group,
                              btn_cancel_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (btn_cancel);
  gtk_object_set_data_full (GTK_OBJECT (xat), "btn_cancel", btn_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btn_cancel);
  gtk_box_pack_start (GTK_BOX (hbox), btn_cancel, FALSE, TRUE, 8);
  gtk_container_set_border_width (GTK_CONTAINER (btn_cancel), 4);
  gtk_widget_add_accelerator (btn_cancel, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btn_cancel, "clicked", accel_group,
                              GDK_Q, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btn_cancel, "clicked", accel_group,
                              GDK_W, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  statusbar = gtk_statusbar_new ();
  gtk_widget_ref (statusbar);
  gtk_object_set_data_full (GTK_OBJECT (xat), "statusbar", statusbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox), statusbar, FALSE, FALSE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (statusbar), 1);

  gtk_signal_connect (GTK_OBJECT (xat), "delete_event",
                      GTK_SIGNAL_FUNC (on_wmain_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (xat), "realize",
                      GTK_SIGNAL_FUNC (on_wmain_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btn_diskusage), "clicked",
                      GTK_SIGNAL_FUNC (on_btn_diskusage_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cb_changeperms), "clicked",
                      GTK_SIGNAL_FUNC (on_cb_changeperms_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cb_changeowner), "clicked",
                      GTK_SIGNAL_FUNC (on_cb_changeowner_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cb_changegroup), "clicked",
                      GTK_SIGNAL_FUNC (on_cb_changegroup_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btn_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_btn_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btn_skip), "clicked",
                      GTK_SIGNAL_FUNC (on_btn_skip_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btn_all), "clicked",
                      GTK_SIGNAL_FUNC (on_btn_all_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btn_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_btn_cancel_clicked),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (xat), accel_group);

  return xat;
}

