ICONS = \
mini-acroread.xpm mini-animate.xpm mini-blender.xpm mini-cheap-call.xpm \
mini-display.xpm mini-elm.xpm mini-gimp.xpm mini-gt.xpm \
mini-gtcd.xpm mini-gvim.xpm mini-kcalc.xpm mini-mpeg_play.xpm \
mini-playmidi.xpm mini-rxvt.xpm mini-soffice.xpm mini-vplay.xpm \
mini-xap.xpm mini-xawtv.xpm mini-xbiff.xpm mini-xcalc.xpm \
mini-xclock.xpm mini-xcpustate.xpm mini-xfig.xpm mini-xfontsel.xpm \
mini-xless.xpm mini-xli.xpm mini-xlock.xpm mini-klock.xpm mini-xman.xpm \
mini-xmixer.xpm mini-xpaint.xpm mini-xterm.xpm mini-xwf.xpm \
mini-xvidcap.xpm mini-netscape.xpm mini-ps2pdf.xpm mini-knews.xpm \
mini-xemacs.xpm mini-wine.xpm mini-editres.xpm mini-winfile.xpm \
mini-xttv.xpm mini-lynx.xpm mini-gzip.xpm mini-gunzip.xpm \
mini-panel.xpm mini-gnome-help-browser.xpm mini-gv.xpm mini-mpg123.xpm \
mini-bzip2.xpm mini-bunzip2.xpm mini-ghex.xpm mini-gnomecal.xpm \
mini-gcolorsel.xpm mini-gnome-ppp.xpm mini-gtt.xpm mini-note.xpm \
mini-quicklist.xpm mini-wxftp.xpm mini-gtop.xpm mini-giram.xpm \
mini-povfront.xpm mini-povray.xpm mini-gpgp.xpm mini-xchat.xpm \
mini-gmurf.xpm mini-realplay.xpm mini-gmix.xpm mini-gmixer.xpm mini-gftp.xpm \
mini-AbiWord.xpm mini-xsetbg.xpm mini-apm.xpm mini-bladeenc.xpm \
mini-applix.xpm mini-ggv.xpm mini-ghostview.xpm mini-gulp.xpm \
mini-artsbuilder.xpm mini-kcontrol.xpm mini-kdehelp.xpm mini-kedit.xpm \
mini-khexdit.xpm mini-kmail.xpm mini-kmedia.xpm mini-kmid.xpm mini-kmidi.xpm \
mini-kmix.xpm mini-xmag.xpm mini-vMac.xpm mini-BasiliskII.xpm \
mini-gnumeric.xpm mini-gnomba.xpm mini-knu.xpm mini-kppp.xpm \
mini-pgaccess.xpm mini-gtv.xpm mini-plaympeg.xpm mini-gphoto.xpm \
mini-LinNeighborhood.xpm mini-xpg.xpm mini-mMosaic.xpm mini-grip.xpm \
mini-gcombust.xpm mini-gtoaster.xpm mini-gnapster.xpm mini-edit.xpm \
mini-xfi.xpm mini-nscal.xpm mini-xconsole.xpm mini-glade.xpm \
mini-sweep.xpm mini-runq.xpm mini-halt.xpm mini-spruce.xpm mini-xeyes.xpm \
mini-blender2.xpm mini-xat.xpm

