/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_xfi (void);
GtkWidget* create_wabout (void);
GtkWidget* create_wfilesel (void);
GtkWidget* create_pmenu (void);
GtkWidget* create_wdirsel (void);
